// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace SimulatronUITest
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// button1
        /// </summary>
        public void button1()
        {
            #region Variable Declarations
            WpfButton uIItemButton = this.UISimulatronWindow.UIItemButton;
            WpfImage uIBgBlueAppearImage = this.UISimulatronWindow.UIBgBlueAppearImage;
            WpfButton uIItemButton1 = this.UISimulatronWindow.UIItemButton1;
            WpfButton uIItemButton2 = this.UISimulatronWindow.UIItemButton2;
            WpfButton uICloseButton = this.UISimulatronWindow.UISimulatronTitleBar.UICloseButton;
            #endregion

            // Click button
            Mouse.Click(uIItemButton, new Point(49, 31));

            // Click button
            Mouse.Click(uIItemButton, new Point(49, 31));

            // Click 'bgBlueAppear' image
            Mouse.Click(uIBgBlueAppearImage, new Point(499, 148));

            // Click button numbered 2 in 'Simulatron' window
            Mouse.Click(uIItemButton1, new Point(20, 6));

            // Click button numbered 2 in 'Simulatron' window
            Mouse.Click(uIItemButton1, new Point(22, 17));

            // Click button numbered 2 in 'Simulatron' window
            Mouse.Click(uIItemButton1, new Point(22, 17));

            // Click button numbered 3 in 'Simulatron' window
            Mouse.Click(uIItemButton2, new Point(44, 21));

            // Click button numbered 3 in 'Simulatron' window
            Mouse.Click(uIItemButton2, new Point(44, 20));

            // Click button numbered 3 in 'Simulatron' window
            Mouse.Click(uIItemButton2, new Point(44, 20));

            // Click button numbered 3 in 'Simulatron' window
            Mouse.Click(uIItemButton2, new Point(44, 20));

            // Click 'Close' button
            Mouse.Click(uICloseButton, new Point(7, 8));
        }
        
        #region Properties
        public UISimulatronWindow UISimulatronWindow
        {
            get
            {
                if ((this.mUISimulatronWindow == null))
                {
                    this.mUISimulatronWindow = new UISimulatronWindow();
                }
                return this.mUISimulatronWindow;
            }
        }
        #endregion
        
        #region Fields
        private UISimulatronWindow mUISimulatronWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UISimulatronWindow : WpfWindow
    {
        
        public UISimulatronWindow()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "Simulatron";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Simulatron");
            #endregion
        }
        
        #region Properties
        public WpfButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton.WindowTitles.Add("Simulatron");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        
        public WpfImage UIBgBlueAppearImage
        {
            get
            {
                if ((this.mUIBgBlueAppearImage == null))
                {
                    this.mUIBgBlueAppearImage = new WpfImage(this);
                    #region Search Criteria
                    this.mUIBgBlueAppearImage.SearchProperties[WpfImage.PropertyNames.AutomationId] = "bgBlueAppear";
                    this.mUIBgBlueAppearImage.WindowTitles.Add("Simulatron");
                    #endregion
                }
                return this.mUIBgBlueAppearImage;
            }
        }
        
        public WpfButton UIItemButton1
        {
            get
            {
                if ((this.mUIItemButton1 == null))
                {
                    this.mUIItemButton1 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton1.SearchProperties[WpfButton.PropertyNames.Instance] = "2";
                    this.mUIItemButton1.WindowTitles.Add("Simulatron");
                    #endregion
                }
                return this.mUIItemButton1;
            }
        }
        
        public WpfButton UIItemButton2
        {
            get
            {
                if ((this.mUIItemButton2 == null))
                {
                    this.mUIItemButton2 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton2.SearchProperties[WpfButton.PropertyNames.Instance] = "3";
                    this.mUIItemButton2.WindowTitles.Add("Simulatron");
                    #endregion
                }
                return this.mUIItemButton2;
            }
        }
        
        public UISimulatronTitleBar UISimulatronTitleBar
        {
            get
            {
                if ((this.mUISimulatronTitleBar == null))
                {
                    this.mUISimulatronTitleBar = new UISimulatronTitleBar(this);
                }
                return this.mUISimulatronTitleBar;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUIItemButton;
        
        private WpfImage mUIBgBlueAppearImage;
        
        private WpfButton mUIItemButton1;
        
        private WpfButton mUIItemButton2;
        
        private UISimulatronTitleBar mUISimulatronTitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UISimulatronTitleBar : WpfTitleBar
    {
        
        public UISimulatronTitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WpfTitleBar.PropertyNames.AutomationId] = "TitleBar";
            this.WindowTitles.Add("Simulatron");
            #endregion
        }
        
        #region Properties
        public WpfButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WpfButton.PropertyNames.AutomationId] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Simulatron");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WpfButton mUICloseButton;
        #endregion
    }
}
